apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logging
resources:
- quickwit.yaml
- vector.yaml

patches:
- target:
    kind: Service
    name: vector
    namespace: logging
  patch: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: vector
    spec:
      type: NodePort
      ports:
        - name: syslog-tcp
          port: 514
          targetPort: 514
          protocol: TCP
          nodePort: 30514
        - name: syslog-udp
          port: 514
          targetPort: 514
          protocol: UDP
          nodePort: 30515
