apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-traipoap-com-tls
spec:
  secretName: app-traipoap-com-tls
  dnsNames:
  - "app.traipoap.com"
  issuerRef:
    name: cluster-ca-issuer
    kind: ClusterIssuer
