apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: app-gateway
  namespace: flux-system
  annotations:
    # Name ref: value must be the name of a ClusterIssuer.
    # The CA issuer is named "cluster-ca-issuer" (infrastructure/configs/cert-manager/ca-issuer.yaml);
    cert-manager.io/cluster-issuer: "cluster-ca-issuer"
spec:
  gatewayClassName: istio
  listeners:
  - name: http
    protocol: HTTP
    port: 9080
    hostname: "flux-web.traipoap.com"
    allowedRoutes:
      namespaces:
        from: "flux-system"
