apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
images:
  - name: ghcr.io/traipoap/backend
    newTag: "0.0.23" # {"$imagepolicy": "production:backend:tag"}
  - name: ghcr.io/traipoap/frontend
    newTag: "0.0.27" # {"$imagepolicy": "production:frontend:tag"}

patches:
  - path: patch-config.yaml
  - path: patch-httproute.yaml

namespace: prod
