apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backend-jwt-secret
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: secretstore-aws
    kind: ClusterSecretStore
  target:
    name: jwt-secret
    creationPolicy: Owner
  data:
  - secretKey: JWT_SECRET
    remoteRef:
      key: dev/backend/jwt
      property: JWT_SECRET
