apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-registry-secret
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: secretstore-aws
    kind: ClusterSecretStore
  target:
    name: github-registry
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "{{ .registry }}": {
                "username": "{{ .username }}",
                "password": "{{ .password }}",
                "email": "{{ .email }}",
                "auth": "{{ printf "%s:%s" .username .password | b64enc }}"
              }
            }
          }
  data:
  - secretKey: registry
    remoteRef:
      key: dev/github-registry/frontend-backend
      property: SERVER

  - secretKey: username
    remoteRef:
      key: dev/github-registry/frontend-backend
      property: USERNAME

  - secretKey: password
    remoteRef:
      key: dev/github-registry/frontend-backend
      property: PASSWORD

  - secretKey: email
    remoteRef:
      key: dev/github-registry/frontend-backend
      property: EMAIL
