---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nfs-provisioner-values
  namespace: networking
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: secretstore-aws
    kind: ClusterSecretStore
  target:
    name: nfs-provisioner-secret-values
    template:
      engineVersion: v2
      data:
        values.yaml: |
          nfs:
            server: "{{ .server }}"
            path: "{{ .path }}"
            reclaimPolicy: Retain
  data:
    - secretKey: server
      remoteRef:
        key: dev/nfs/config
        property: SERVER
    - secretKey: path
      remoteRef:
        key: dev/nfs/config
        property: PATH
